version: "3.8"

services:
  service:
    build:
      context: .
      ssh:
        - default=${GM_SDK_GIT_SSH_KEY:-$HOME/.ssh/id_rsa}
    image: thought-agent:latest
    restart: unless-stopped
    ports:
      - 18002:7788